### ISSUE TITLE
Multiple null pointer dereferences (DoS) in Cd00Player

### ISSUE THREAD

**Issue by debrouxl** [adplug/adplug#101]
Offending samples: [nullptr_deref_1.tar.gz](https://github.com/adplug/adplug/files/3526965/nullptr_deref.tar.gz), [nullptr_deref_2.tar.gz](https://github.com/adplug/adplug/files/3526966/nullptr_deref.tar.gz).

Output:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9667==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f6bfd0459e0 bp 0x7ffed37d9490 sp 0x7ffed37d9300 T0)
==9667==The signal is caused by a READ memory access.
==9667==Hint: address points to the zero page.
    #0 0x7f6bfd0459df in LE_WORD(unsigned short const*) .../adplug/src/d00.cpp:46:11
    #1 0x7f6bfd0459df in Cd00Player::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/d00.cpp:122
    #2 0x7f6bfd00ec3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #3 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #4 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #5 0x7f6bfc41d09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #6 0x4208b9 in _start (.../adplug_prefix/bin/adplay+0x4208b9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV .../adplug/src/d00.cpp:46:11 in LE_WORD(unsigned short const*)
==9667==ABORTING

AddressSanitizer:DEADLYSIGNAL
=================================================================
==9545==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f0511a2a731 bp 0x7fff3b3d85d0 sp 0x7fff3b3d8440 T0)
==9545==The signal is caused by a READ memory access.
==9545==Hint: address points to the zero page.
    #0 0x7f0511a2a730 in Cd00Player::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/d00.cpp:119:20
    #1 0x7f05119f3c3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #2 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #3 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #4 0x7f0510e0209a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #5 0x4208b9 in _start (.../adplug_prefix/bin/adplay+0x4208b9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV .../adplug/src/d00.cpp:119:20 in Cd00Player::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&)
==9545==ABORTING
```

**Comment by Malvineous** [comment]
Closing thanks to fixes provided by @miller-alex, thanks for the report and especially the fixes!
