### ISSUE TITLE
Multiple OOB reads in Cu6mPlayer::get_next_codeword()

### ISSUE THREAD

**Issue by debrouxl** [adplug/adplug#92]
I didn't plan on doing that a couple days ago, but after the discussion in issue #91, I felt like checking whether fixing the DF in the class made it easier to hit other unreported issues, especially in that file.
Indeed, AFL++'s afl-fuzz quickly produced several samples crashing at locations not reported by fcambus several days ago; however, while of them are in classes declared after `Cu6mPlayer` in `CAdPlug::allplayers`, the problems are hit the same way even when restoring the DF.

Let's start with a heap-based OOB read on an extremely small file, which should be non-crashing in a standard build, but still worth fixing. For some reason, I can't seem to be able to attach the gzipped file, so here are the contents of that 8-byte file as a hex dump:
```
53 7f 00 00 00 ff 7f 00
```

Output:
```
=================================================================
==14316==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000005d5 at pc 0x7fb4c13056f3 bp 0x7ffcbdc01850 sp 0x7ffcbdc01848
READ of size 1 at 0x6020000005d5 thread T0
    #0 0x7fb4c13056f2 in Cu6mPlayer::get_next_codeword(long&, unsigned char*, int) .../adplug/src/u6m.cpp:323:8
    #1 0x7fb4c13056f2 in Cu6mPlayer::lzw_decompress(Cu6mPlayer::data_block, Cu6mPlayer::data_block) .../adplug/src/u6m.cpp:223
    #2 0x7fb4c1303b1d in Cu6mPlayer::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/u6m.cpp:84:8
    #3 0x7fb4c11a5c3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13


    #4 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #5 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #6 0x7fb4c05b409a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4208b9 in _start (.../adplug_prefix/bin/adplay+0x4208b9)

0x6020000005d5 is located 0 bytes to the right of 5-byte region [0x6020000005d0,0x6020000005d5)
allocated by thread T0 here:
    #0 0x4f7ad2 in operator new[](unsigned long) (.../adplug_prefix/bin/adplay+0x4f7ad2)
    #1 0x7fb4c1303a44 in Cu6mPlayer::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/u6m.cpp:70:41
    #2 0x7fb4c11a5c3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #3 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #4 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #5 0x7fb4c05b409a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: heap-buffer-overflow .../adplug/src/u6m.cpp:323:8 in Cu6mPlayer::get_next_codeword(long&, unsigned char*, int)
Shadow bytes around the buggy address:
  0x0c047fff8060: fa fa 00 03 fa fa 00 03 fa fa 06 fa fa fa 06 fa
  0x0c047fff8070: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff8080: fa fa 04 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff8090: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff80a0: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 00 03
=>0x0c047fff80b0: fa fa 06 fa fa fa fd fd fa fa[05]fa fa fa fa fa
  0x0c047fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==14316==ABORTING
```

**Comment by debrouxl** [comment]
More samples, which seem to show multiple locations: [heap_OOBRs.tar.gz](https://github.com/adplug/adplug/files/3526748/heap_OOBRs.tar.gz).
