### ISSUE TITLE
Multiple OOB reads in CxadbmfPlayer::xadplayer_load()

### ISSUE THREAD

**Issue by debrouxl** [adplug/adplug#93]
This is in the vicinity of #85 , but a different stack trace. Like in issue #92 , I can't seem to be able to attach files right now, so here's a hex dump of the tiny offending sample:
```
42 4d 46 00 64 42 4d 46 00 64 4d 4d
```
Output:
```
=================================================================
==31205==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000005dc at pc 0x0000004c77b6 bp 0x7ffec9bb3450 sp 0x7ffec9bb2c00
READ of size 13 at 0x6020000005dc thread T0
    #0 0x4c77b5 in __asan_memcpy (.../adplug_prefix/bin/adplay+0x4c77b5)
    #1 0x7fbac39afddd in CxadbmfPlayer::xadplayer_load() .../adplug/src/bmf.cpp:169:7
    #2 0x7fbac3b31693 in CxadPlayer::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/xad.cpp:93:8
    #3 0x7fbac39a0c3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #4 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #5 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #6 0x7fbac2daf09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4208b9 in _start (.../adplug_prefix/bin/adplay+0x4208b9)

0x6020000005dc is located 0 bytes to the right of 12-byte region [0x6020000005d0,0x6020000005dc)
allocated by thread T0 here:
    #0 0x4f7ad2 in operator new[](unsigned long) (.../adplug_prefix/bin/adplay+0x4f7ad2)
    #1 0x7fbac3b315fb in CxadPlayer::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/xad.cpp:89:9
    #2 0x7fbac39a0c3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #3 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #4 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #5 0x7fbac2daf09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (.../adplug_prefix/bin/adplay+0x4c77b5) in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c047fff8060: fa fa 00 03 fa fa 00 03 fa fa 06 fa fa fa 06 fa
  0x0c047fff8070: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff8080: fa fa 04 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff8090: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff80a0: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 00 03
=>0x0c047fff80b0: fa fa 06 fa fa fa fd fd fa fa 00[04]fa fa fa fa
  0x0c047fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==31205==ABORTING
```

**Comment by debrouxl** [comment]
More samples: [heap_OOBRs.tar.gz](https://github.com/adplug/adplug/files/3526732/heap_OOBRs.tar.gz).
