### ISSUE TITLE
OOB read in CrixPlayer::data_initial()

### ISSUE THREAD

**Issue by debrouxl** [adplug/adplug#94]
Unlike the two other OOB reads I've just posted, this one is > 0 bytes after the end of the allocated memory block. The loader should probably bail out early if the file size is clearly too small to contain a valid RIX file.

Offending sample hex dump:
```
aa 55
```
Output:
```
=================================================================
==14540==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000067d at pc 0x7f80c9a62239 bp 0x7ffdf279d440 sp 0x7ffdf279d438
READ of size 1 at 0x60200000067d thread T0
    #0 0x7f80c9a62238 in CrixPlayer::data_initial() .../adplug/src/rix.cpp:196:16
    #1 0x7f80c9a62238 in CrixPlayer::rewind(int) .../adplug/src/rix.cpp:149
    #2 0x7f80c9a61467 in CrixPlayer::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/rix.cpp:101:3
    #3 0x7f80c9951c3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #4 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #5 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #6 0x7f80c8d6009a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4208b9 in _start (.../adplug_prefix/bin/adplay+0x4208b9)

0x60200000067d is located 10 bytes to the right of 3-byte region [0x602000000670,0x602000000673)
allocated by thread T0 here:
    #0 0x4f7ad2 in operator new[](unsigned long) (.../adplug_prefix/bin/adplay+0x4f7ad2)
    #1 0x7f80c9a61108 in CrixPlayer::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/rix.cpp:93:17
    #2 0x7f80c9951c3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #3 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #4 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #5 0x7f80c8d6009a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: heap-buffer-overflow .../adplug/src/rix.cpp:196:16 in CrixPlayer::data_initial()
Shadow bytes around the buggy address:
  0x0c047fff8070: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff8080: fa fa 04 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff8090: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 06 fa
  0x0c047fff80a0: fa fa 06 fa fa fa 06 fa fa fa 06 fa fa fa 00 03
  0x0c047fff80b0: fa fa 06 fa fa fa fd fd fa fa fd fd fa fa fd fd
=>0x0c047fff80c0: fa fa fd fd fa fa fd fd fa fa fd fa fa fa 03[fa]
  0x0c047fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff80f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==14540==ABORTING
```

**Comment by debrouxl** [comment]
Another sample: [heap_OOBR.tar.gz](https://github.com/adplug/adplug/files/3526717/heap_OOBR.tar.gz).
