### ISSUE TITLE
Floating-point exception abort (DoS) in CmidPlayer::rewind()

### ISSUE THREAD

**Issue by debrouxl** [adplug/adplug#95]
Hex dump of the tiny offending sample:
```
43 54 4d 46
```
Output:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==14508==ERROR: AddressSanitizer: FPE on unknown address 0x7f154c9d5cd8 (pc 0x7f154c9d5cd8 bp 0x000000000000 sp 0x7ffe951ab7c0 T0)
    #0 0x7f154c9d5cd7 in CmidPlayer::rewind(int) .../adplug/src/mid.cpp:952:30
    #1 0x7f154c9c07d0 in CmidPlayer::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CFileProvider const&) .../adplug/src/mid.cpp:344:5
    #2 0x7f154c90cc3a in CAdPlug::factory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Copl*, CPlayers const&, CFileProvider const&) .../adplug/src/adplug.cpp:182:13
    #3 0x4fd913 in play(char const*, Player*, int) .../adplay-unix/src/adplay.cc:309:11
    #4 0x4fd913 in main .../adplay-unix/src/adplay.cc:554
    #5 0x7f154bd1b09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #6 0x4208b9 in _start (.../adplug_prefix/bin/adplay+0x4208b9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE .../adplug/src/mid.cpp:952:30 in CmidPlayer::rewind(int)
==14508==ABORTING
```

**Comment by debrouxl** [comment]
Another sample: [div_0.tar.gz](https://github.com/adplug/adplug/files/3526712/div_0.tar.gz).
